MaxZombieSpawn: 70
MaxMonstersSpawn: 35
ZombieDamage: 5
ZombieHealth: 16
ZombieSpeed: 2
FoodChange: 1
AnimalsCanSpawn: true
AllowCustomDrop: true
CustomDropRate: 25
ItemDrop:
  item1:
    id: 367
    damage: 0
    dropRate: 25
  item2:
    id: 267
    damage: 0
    dropRate: 1
SpawnFrequency: 50
SpawnLimit: 100
StatsSaving: 10