author: Olivier Cosquer
description: Play-4-Elements - Bukkit France - ApocalypseZombie
name: ApocalypseZombie
version: 0.3.5
main: fr.oliviercosquer.ApocalypseZombie.ApocalypseZombie
load: STARTUP
url: http://play-4-elements.fr